import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarFB from "@/components/UI/NabvarFB";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <NavbarFB/>
        {children}
        </body>
    </html>
  );
}
